spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students-db
    username: postgres
    password: 
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update),production set to none or comment it
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
server:
  port: 8091 